### ISSUE TITLE
无法运行前端页面

### ISSUE THREAD

**Issue by kwangq** [PieceOfFall/-#6]
在运行npm run serve的时候报错，显示如下
PS C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end> npm run serve  

> book-manage@0.1.0 serve
> vue-cli-service serve

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
10% building 0/1 modules 1 active ...r\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\hot\dev-server.js ./src/ma10% building 2/4 modules 2 active ...s\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\hot\dev-serv10% building 2/5 modules 3 active ...loader\lib\index.js!C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\src\main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:373:3    
    at iterateNormalLoaders (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:236:3    
    at runSyncOrAsync (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:373:3    
    at iterateNormalLoaders (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\Administrator\Desktop\图书管理系统\BookManage\front_end\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.10.0

**Comment by PieceOfFall** [comment]
https://blog.csdn.net/qq_38290251/article/details/130525692

**Comment by PieceOfFall** [comment]
搞定了没，没反应我就关了
